name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload site to Neocities
      run: |
        zip -r site.zip . -x ".git/*" ".github/*"
        curl -H "Authorization: Bearer ${{ secrets.NEOCITIES_API_KEY }}" \
          -F "file=@site.zip" \
          https://neocities.org/api/upload
